
[versions]
agp = "8.11.2"
androidDesugaring = "2.1.5"
dokka = "2.1.0"
graalVmNative = "0.11.2"
kiteui = "6.1.0-prerelease-57"
kotlin = "2.2.20"
kotlinxCoroutinesTest = "1.10.2"
kotlinxSerializationCsvDurable = "0.2.21-1"
ksp = "2.2.20-2.0.3"
lightningServer = "5.0.0-prerelease-223"
lkGradleHelpers = "4.0.6"
proguard = "7.8.1"
serviceAbstractions = "0.0.1-82"
shadow = "8.1.1"
vanniktechPublishing = "0.34.0"
vite = "0.6.0" # Don't update to 0.6.3, it is broke

[libraries]
androidDesugaring = { module = "com.android.tools:desugar_jdk_libs", version = { ref = "androidDesugaring" } }
comLightningKiteServices-database-processor = { module = "com.lightningkite.services:database-processor", version = { ref = "serviceAbstractions" } }
comLightningKiteServices-database-shared = { module = "com.lightningkite.services:database-shared", version = { ref = "serviceAbstractions" } }
comLightningkiteKiteuiLibrary = { module = "com.lightningkite.kiteui:library", version = { ref = "kiteui" } }
comLightningkiteKotlinxSerializationCsvDurable = { module = "com.lightningkite:kotlinx-serialization-csv-durable", version = { ref = "kotlinxSerializationCsvDurable" } }
comLightningkiteLightningserver-core-shared = { module = "com.lightningkite.lightningserver:core-shared", version = { ref = "lightningServer" } }
comLightningkiteLightningserver-files-shared = { module = "com.lightningkite.lightningserver:files-shared", version = { ref = "lightningServer" } }
comLightningkiteLightningserver-sessions-shared = { module = "com.lightningkite.lightningserver:sessions-shared", version = { ref = "lightningServer" } }
comLightningkiteLightningserver-typed = { module = "com.lightningkite.lightningserver:typed", version = { ref = "lightningServer" } }
comLightningkiteLightningserver-typed-shared = { module = "com.lightningkite.lightningserver:typed-shared", version = { ref = "lightningServer" } }
kotlinxCoroutinesTest = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version = { ref = "kotlinxCoroutinesTest" } }
lkGradleHelpers = { module = "com.lightningkite:lk-gradle-helpers", version = { ref = "lkGradleHelpers" } }
proguard = { module = "com.guardsquare:proguard-gradle", version = { ref = "proguard" } }

[plugins]
androidApp = { id = "com.android.application", version = { ref = "agp" } }
androidLibrary = { id = "com.android.library", version = { ref = "agp" } }
comLightningkiteKiteui = { id = "com.lightningkite.kiteui", version = { ref = "kiteui" } }
dokka = { id = "org.jetbrains.dokka", version = { ref = "dokka" } }
graalVmNative = { id = "org.graalvm.buildtools.native", version = { ref = "graalVmNative" } }
kotlinCocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version = { ref = "kotlin" } }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version = { ref = "kotlin" } }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version = { ref = "kotlin" } }
ksp = { id = "com.google.devtools.ksp", version = { ref = "ksp" } }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version = { ref = "kotlin" } }
shadow = { id = "com.github.johnrengelman.shadow", version = { ref = "shadow" } }
vanniktechPublishing = { id = "com.vanniktech.maven.publish", version = { ref = "vanniktechPublishing" } }
vite = { id = "dev.opensavvy.vite.kotlin", version = { ref = "vite" } }