
[versions]
agp = "8.2.2"
androidDesugaring = "2.1.4"
deployHelpers = "0.0.7"
dokka = "1.9.20"
graalVmNative = "0.9.24"
kotlin = "2.0.21"
kotlinerCli = "1.0.5"
ksp = "2.0.21-1.0.25"
ktor = "3.0.3"
proguard = "7.3.2"
shadow = "8.1.1"
vanniktechMavenPublish = "0.30.0"
vite = "0.4.0"

[libraries]
androidDesugaring = { module = "com.android.tools:desugar_jdk_libs", version = { ref = "androidDesugaring" } }
comLightningkiteKiteuiLibrary = { module = "com.lightningkite.kiteui:library", version = "4.0.12" }
comLightningkiteLightningserverProcessor = { module = "com.lightningkite.lightningserver:processor", version = "4.1.11" }
comLightningkiteLightningserverServerAws = { module = "com.lightningkite.lightningserver:server-aws", version = "4.1.11" }
comLightningkiteLightningserverServerAzure = { module = "com.lightningkite.lightningserver:server-azure", version = "4.1.11" }
comLightningkiteLightningserverServerCore = { module = "com.lightningkite.lightningserver:server-core", version = "4.1.11" }
comLightningkiteLightningserverServerDynamodb = { module = "com.lightningkite.lightningserver:server-dynamodb", version = "4.1.11" }
comLightningkiteLightningserverServerFirebase = { module = "com.lightningkite.lightningserver:server-firebase", version = "4.1.11" }
comLightningkiteLightningserverServerKtor = { module = "com.lightningkite.lightningserver:server-ktor", version = "4.1.11" }
comLightningkiteLightningserverServerMemcached = { module = "com.lightningkite.lightningserver:server-memcached", version = "4.1.11" }
comLightningkiteLightningserverServerMongo = { module = "com.lightningkite.lightningserver:server-mongo", version = "4.1.11" }
comLightningkiteLightningserverServerRedis = { module = "com.lightningkite.lightningserver:server-redis", version = "4.1.11" }
comLightningkiteLightningserverServerSentry = { module = "com.lightningkite.lightningserver:server-sentry", version = "4.1.11" }
comLightningkiteLightningserverServerSftp = { module = "com.lightningkite.lightningserver:server-sftp", version = "4.1.11" }
comLightningkiteLightningserverServerTesting = { module = "com.lightningkite.lightningserver:server-testing", version = "4.1.11" }
comLightningkiteLightningserverShared = { module = "com.lightningkite.lightningserver:shared", version = "4.1.11" }
kotlinerCli = { module = "com.lightningkite:kotliner-cli", version = { ref = "kotlinerCli" } }
ktorCallLogging = { module = "io.ktor:ktor-server-call-logging", version = { ref = "ktor" } }
proguard = { module = "com.guardsquare:proguard-gradle", version = { ref = "proguard" } }

[plugins]
androidApp = { id = "com.android.application", version = { ref = "agp" } }
androidLibrary = { id = "com.android.library", version = { ref = "agp" } }
comLightningkiteKiteui = { id = "com.lightningkite.kiteui", version = "4.0.7" }
dokka = { id = "org.jetbrains.dokka", version = { ref = "dokka" } }
graalVmNative = { id = "org.graalvm.buildtools.native", version = { ref = "graalVmNative" } }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version = { ref = "kotlin" } }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version = { ref = "kotlin" } }
ksp = { id = "com.google.devtools.ksp", version = { ref = "ksp" } }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version = { ref = "kotlin" } }
shadow = { id = "com.github.johnrengelman.shadow", version = { ref = "shadow" } }
vanniktechMavenPublish = { id = "com.vanniktech.maven.publish", version = { ref = "vanniktechMavenPublish" } }
vite = { id = "dev.opensavvy.vite.kotlin", version = { ref = "vite" } }